# -*- coding: utf-8 -*-
"""
/***************************************************************************
 cubaroad
                                 A QGIS plugin
 This is an adaptation of the CubaRoad app for in qgis uses
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-03-27
        copyright            : (C) 2024 by Cosylval
        email                : yoann.zenner@viacesi.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load cubaroad class from file cubaroad.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cubaroad import cubaroad
    return cubaroad(iface)
